config/routes.rb
Rails.application.routes.draw do
  get 'home/download'

  get 'home/file_upload'
  post 'home/upload'

  get 'books/index_ajax'
  get 'books/search_ajax'
  get 'books/search'
  resources :books, only: [:index, :new, :create, :show]

  get 'home/button_param'

  get 'home/calendar'

  get 'home/dateselect'

  get 'home/page_top'

  devise_for :users
  get 'home/index'

  root 'home#index'

end

app/models/book.rb
require 'csv'

class Book < ActiveRecord::Base
  mount_uploader :cover, CoverUploader

  class << self
    def search( search_params )
      books = Book.all
      books = search_title(search_params, books) if search_params[:title].present?
      books = search_author(search_params, books) if search_params[:author].present?
      books = search_publisher(search_params, books) if search_params[:publisher].present?

      books = search_isbn(search_params, books) if search_params[:isbn].present?
      books
    end

    def search_title( search_params, books )
      books = books.where("title LIKE ?", "%#{escape_like search_params[:title]}%")
    end

    def search_author( search_params, books )
      books = books.where("author LIKE ?", "%#{escape_like search_params[:author]}%")
    end

    def search_publisher( search_params, books )
      books = books.where("publisher LIKE ?", "%#{escape_like search_params[:publisher]}%")
    end

    def search_isbn( search_params, books )
      books = books.where("isbn LIKE ?", "%#{escape_like search_params[:isbn]}%")
    end

    def to_csv( books )
      headers = %w(id title auther publisher isbn cover)  
      contents = CSV.generate(headers: headers, write_headers: true, force_quotes: false) do |csv|
        books.each do |row|
          csv << [row.id, row.title, row.author, row.publisher, row.isbn, row.cover]
        end
      end
      contents.encode(Encoding::SJIS)
    end
  end
end

app/models/book_search_form.rb
class BookSearchForm
  include ActiveModel::Model
  attr_accessor :title
  attr_accessor :author
  attr_accessor :publisher
  attr_accessor :isbn
  validates :title, length: { maximum: 20 }
  validates :author, length: { maximum: 20 }
  validates :publisher, length: { maximum: 20 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_uniqueness_of :username
  validates_presence_of :username

  #login_idを利用してログインするようにオーバーライド
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      #認証の条件式を変更する
      where(conditions).where(["login_id = :value", { :value => login_id }]).first
    else
      where(conditions).first
    end
  end

  #登録時にemailを不要とする
  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Exception, with: :error500
  rescue_from ActiveRecord::RecordNotFound, ActionController::RoutingError, with: :error404

  private

  def error404(e)
    render 'error404', status: 404, formats: [:html]
  end

  def error500(e)
    logger.error [e, *e.backtrace].join("\n")
    render 'error500', status: 500, formats: [:html]
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :login_id << :username
    devise_parameter_sanitizer.for(:sign_in) << :login_id << :username
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show]

  def search
    @book_search_form = BookSearchForm.new
  end

  def index
    @book_search_form = BookSearchForm.new(params[:book_search_form])

    @books = Book.search params[:book_search_form] if params[:csv]

    render :search and return unless @book_search_form.valid?
    send_data Book.to_csv(@books), type: 'text/csv; charset=shift_jis', filename: "books.csv" if params[:csv].present?
  end

  def search_ajax
    @book_search_form = BookSearchForm.new
  end

  def index_ajax
    @books = Book.search params[:book_search_form]
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: t('messages.created_book') }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  private

    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:title, :author, :publisher, :isbn, :cover, :cover_cache, :remove_cover)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def page_top
  end

  def dateselect
  end

  def calendar
  end

  def button_param
    @sample_data = params[:sample_data]
  end

  def file_upload
  end

  def upload
    work_path = 'tmp/files'
    FileUtils.mkdir_p(work_path) unless FileTest.exist?(work_path)
    @filenames = (params[:uploads] || []).each_with_object([]) do |file, files|
      FileUtils.cp file.tempfile, "#{work_path}/#{file.original_filename}"
      files << file.original_filename
    end

    render :file_upload
  end

  def download
    work_path = 'tmp/files'
    render :file_upload and return if params[:file_name].blank?

    send_file "#{work_path}/#{params[:file_name]}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/application/error404.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Page Not Found</title>
  </head>

  <body>
    Page Not Found
  </body>
</html>

app/views/application/error500.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>We're sorry, but something went wrong (500)</title>
  </head>

  <body>
    We're sorry, but something went wrong (500)
  </body>
</html>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <h2><%= pluralize(@book.errors.count, "error") %></h2>

        <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="row form-group">
    <div class="col-md-2">
      <%= f.label :title %><br>
    </div>
    <div class="col-md-2">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>

  <div class="row form-group">
    <div class="col-md-2">
      <%= f.label :author %><br>
    </div>
    <div class="col-md-2">
      <%= f.text_field :author, class: "form-control" %>
    </div>
  </div>

  <div class="row form-group">
    <div class="col-md-2">
      <%= f.label :publisher %><br>
    </div>
    <div class="col-md-2">
      <%= f.text_field :publisher, class: "form-control" %>
    </div>
  </div>

  <div class="row form-group">
    <div class="col-md-2">
      <%= f.label :isbn %><br>
    </div>
    <div class="col-md-2">
      <%= f.text_field :isbn, class: "form-control" %>
    </div>
  </div>

  <div class="row form-group">
    <div class="col-md-2">
      <%= f.label :cover %><br>
    </div>
    <div class="col-md-4">
      <%= image_tag(@book.cover_url) if @book.cover? %>
      <%= f.file_field :cover, class: "filestyle" %>
      <%= f.hidden_field :cover_cache %>
      <label>
        <%= f.check_box :remove_cover %> Remove Cover
      </label>
    </div>
  </div>

  <div class="row form-group">
    <div class="col-md-2">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>

  <br/>
<% end %>

app/views/books/_index_ajax.html.erb
<H3>検索結果</H3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>No</th>
      <th>title</th>
      <th>author</th>
      <th>publisher</th>
      <th>isbn</th>
    </tr>
  </thead>

  <tbody>
    <% (@books || []).each_with_index do |book, index| %>
      <tr>
        <td><%= "#{index + 1}" %></td>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.publisher %></td>
        <td><%= book.isbn %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/index.html.erb
<h1>Books#index</h1>
<p>Find me in app/views/books/index.html.erb</p>

app/views/books/index_ajax.html.erb
<h1>Books#index_ajax</h1>
<p>Find me in app/views/books/index_ajax.html.erb</p>

app/views/books/index_ajax.js.erb
$('#results').html("<%= j render 'index_ajax' %>")
window.location = '#results'

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<div class="row">
  <div class="col-md-1">
    <%= link_to 'Back', root_path, class: "btn btn-default" %>
  </div>
</div>

app/views/books/search.html.erb
<H3>検索フォームオブジェクトで検索条件を受け取る</H3>

<%= form_for @book_search_form, url: books_path, method: :get do |f| %>
  <% if @book_search_form.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <%= pluralize(@book_search_form.errors.count, "error") %>
        <ul>
        <% @book_search_form.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="row form-group">
    <div class="col-md-2">
      <%= f.label :title %>
    </div>
    <div class="col-md-2">
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>

  <div class="row form-group">
    <div class="col-md-2">
      <%= f.label :author %>
    </div>
    <div class="col-md-2">
      <%= f.text_field :author, class: 'form-control' %>
    </div>
  </div>

  <div class="row form-group">
    <div class="col-md-2">
      <%= f.label :publisher %>
    </div>
    <div class="col-md-2">
      <%= f.text_field :publisher, class: 'form-control' %>
    </div>
  </div>

  <div class="row form-group">
    <div class="col-md-2">
      <%= f.label :isbn %>
    </div>
    <div class="col-md-2">
      <%= f.text_field :isbn, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <%= f.submit '検索', class: 'btn btn-primary' %>
  </div>

<hr/>
<H3>CSVダウンロード</H3>
  <div class="row form-group">
    <div class="col-md-2">
      <%= f.submit '検索結果をCSVでダウンロード', class: "btn btn-default", name: "csv" %>
    </div>
  </div>
<% end %>

app/views/books/search_ajax.html.erb
<H3>検索結果をAjaxで受け取る</H3>

<%= form_for @book_search_form, url: books_index_ajax_path, method: :get, remote: true do |f| %>
  <% if @book_search_form.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <%= pluralize(@book_search_form.errors.count, "error") %>
        <ul>
        <% @book_search_form.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="row form-group">
    <div class="col-md-2">
      <%= f.label :title %>
    </div>
    <div class="col-md-2">
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>

  <div class="row form-group">
    <div class="col-md-2">
      <%= f.label :author %>
    </div>
    <div class="col-md-2">
      <%= f.text_field :author, class: 'form-control' %>
    </div>
  </div>

  <div class="row form-group">
    <div class="col-md-2">
      <%= f.label :publisher %>
    </div>
    <div class="col-md-2">
      <%= f.text_field :publisher, class: 'form-control' %>
    </div>
  </div>

  <div class="row form-group">
    <div class="col-md-2">
      <%= f.label :isbn %>
    </div>
    <div class="col-md-2">
      <%= f.text_field :isbn, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <%= f.submit '検索', class: 'btn btn-primary' %>
  </div>

<% end %>

<hr/>
<div id="results">
</div>

app/views/books/show.html.erb
<h1>Book</h1>

<div class="row">
  <div class="col-md-2">
    <%= t('activerecord.attributes.book.title') %>
  </div>
  <div class="col-md-2">
    <%= @book.title %>
  </div>
</div>

<br/>

<div class="row">
  <div class="col-md-2">
    <%= t('activerecord.attributes.book.author') %>
  </div>
  <div class="col-md-2">
    <%= @book.author %>
  </div>
</div>

<br/>

<div class="row">
  <div class="col-md-2">
    <%= t('activerecord.attributes.book.publisher') %>
  </div>
  <div class="col-md-2">
    <%= @book.publisher %>
  </div>
</div>

<br/>

<div class="row">
  <div class="col-md-2">
    <%= t('activerecord.attributes.book.isbn') %>
  </div>
  <div class="col-md-2">
    <%= @book.isbn %>
  </div>
</div>

<div class="row">
  <div class="col-md-2">
    <%= t('activerecord.attributes.book.cover') %>
  </div>
  <div class="col-md-2">
    <%= image_tag(@book.cover_url) if @book.cover? %>
  </div>
</div>

<br/>

app/views/home/_toplink.html.erb
<span id="top-link-block" class="hidden">
  <a href="#" class="well well-sm" onclick="$('html,body').animate({scrollTop:0},'normal');return false;">
    <span class="glyphicon glyphicon-chevron-up"></span>
  </a>
</span>

app/views/home/button_param.html.erb
<H3>ボタンクリック時にパラメータを渡す</H3>

<%= link_to 'パラメータ渡す', home_button_param_path(sample_data: 'abc'), method: :get, class: "btn btn-primary" %>

パラメータ：<%= @sample_data %>

app/views/home/calendar.html.erb
<H3>カレンダーを使って日付を入力する</H3>

<div class="row">
  <div class="col-md-2">
    Gem利用
  </div>
  <div class="col-md-2">
    <div class="form-group">
      <div class='input-group date' id='datetimepicker1'>
        <input type='text' name='sample[date]'class="form-control" data-date-format="YYYY/MM/DD"/>
        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
        </span>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-2">
    date_field利用
  </div>
  <div class="col-md-2">
    <%= date_field_tag '日付' %>
  </div>
</div>

app/views/home/dateselect.html.erb
<H3>dateselectにbootstrapを適用する</H3>

<div class="row">
  <div class="col-md-2">
    <%== sprintf(date_select('sample[date]', '', {use_month_numbers: true, start_year: (Date.today.years_ago 10).year, end_year: Date.today.year, discard_day: true, date_separator: '%s'}, {class: "form-control"}), '年') + '月' %>
  </div>
  <div class="col-md-3">
    <%== sprintf(date_select('sample[date]', '', {use_month_numbers: true, start_year: (Date.today.years_ago 10).year, end_year: Date.today.year, discard_day: false, date_separator: '%s'}, {class: "form-control"}), '年', '月') + '日' %>
  </div>
</div>

app/views/home/file_upload.html.erb
<h1>ファイルアップロード/ダウンロード</h1>

<div>
  <%= form_tag home_upload_path, :method => :post, :multipart => true do %>
    <div class="row">
      <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <%= file_field_tag 'uploads[]', class: "filestyle", :multiple => true %>
      </div>
      <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1">
        <%= submit_tag 'Add Files', class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

<hr/>

<div>
  <% (@filenames || []).each do |f| %>
    file: <%= link_to f, home_download_path(file_name: f) %><br/>
  <% end %>
</div>

app/views/home/index.html.erb
<div>
  <%= link_to 'ページトップに戻る機能', home_page_top_path %>
</div>
<div>
  <%= link_to 'dateselectにbootstrapを適用する', home_dateselect_path %>
</div>
<div>
  <%= link_to 'カレンダーを使って日付を入力する', home_calendar_path %>
</div>
<div>
  <%= link_to 'ボタンクリック時にパラメータを渡す', home_button_param_path %>
</div>
<div>
  <%= link_to '検索フォームオブジェクトで検索条件を受け取る', books_search_path %>
</div>
<div>
  <%= link_to '検索結果をAjaxで受け取る', books_search_ajax_path %>
</div>
<div>
  <%= link_to 'ファイルアップロード/ダウンロード', home_file_upload_path %>
</div>
<div>
  <%= link_to 'ファイルアップロード(CarrierWave)', new_book_path %>
</div>
<div>
  <%= link_to 'CSVダウンロード', books_search_path %>
</div>

app/views/home/page_top.html.erb
<H3>ページトップに戻る機能</H3>
<div>
  <% 100.times.each_with_index do |i| %>
    <%= "#{i}" %><br/>
  <% end %>
</div>

<%= render partial: 'toplink' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Toybox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
      </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Toybox', root_path, class: 'navbar-brand' %></li>
        <% if user_signed_in? %>
        <li class="pull-right"><%= link_to "", destroy_user_session_path, :method => :delete, class: "glyphicon glyphicon-log-out" %></li>
        <% end %>
      </ul>
    </div>
  </header>

  <div class="container">
    <% if notice %>
      <div class="alert alert-success" role="alert"><%= notice %></div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger" role="alert"><%= alert %></div>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>